# Em uma eleição existem quatro candidatos. Os votos são informados por meio
# de códigos. Os dados utilizados para a contagem dos votos obedecem à seguinte
# codificação:
# - 1, 2, 3, 4 = voto para os respectivos candidatos;
# - 5 = voto nulo;
# - 6 = voto em branco;
# Elabore um script em linguagem Python que leia o código do candidato em um
# voto. Calcule e mostre:
# - total de votos para cada candidato;
# - total de votos nulos;
# - total de votos em branco;
# Como finalizador do conjunto de votos, tem-se o valor 0.


